# Generated by Django 4.0.5 on 2022-07-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_termino',
            field=models.DateField(null=True),
        ),
    ]
