# Generated by Django 4.0.5 on 2022-07-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_descuento_producto_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_termino',
        ),
        migrations.AddField(
            model_name='producto',
            name='Dias_vigencia',
            field=models.IntegerField(default=0),
        ),
    ]
