# Generated by Django 4.0.5 on 2022-07-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_producto_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Dias_vigencia',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_termino',
            field=models.DateField(null=True),
        ),
    ]
