# Generated by Django 4.0.5 on 2022-07-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_producto_dias_vigencia_producto_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
