# Generated by Django 4.0.5 on 2022-07-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_producto_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
