# Generated by Django 4.0.4 on 2022-07-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_promociones_remove_producto_descuento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promociones',
            new_name='Promocion',
        ),
    ]
