# Generated by Django 4.0.4 on 2022-07-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_promociones_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado_promocion',
            field=models.BooleanField(default=False),
        ),
    ]
