# Generated by Django 4.0.4 on 2022-07-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_producto_precio_promo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_promo',
            new_name='precio_antiguo',
        ),
    ]
