# Generated by Django 4.0.4 on 2022-07-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='fecha',
            field=models.DateField(default='2020-07-08'),
        ),
    ]
