# Generated by Django 4.0.4 on 2022-07-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historial_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
