# Generated by Django 4.0.4 on 2022-07-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_historial_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
